### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by debsahu** [simap/Ws2812Adapter#1]
Could you add a simple example? Thanks!

**Comment by simap** [comment]
It has the same API as Apa102Adapter:

https://github.com/simap/Apa102Adapter/blob/master/examples/strandtest/strandtest.ino

that should work if you replace Apa102Adapter for Ws2812Adapter.

**Comment by debsahu** [comment]
thank you!

**Comment by debsahu** [comment]
Is there a way to send uint8_t * data stored as array of r, g & b. Something like here: https://github.com/debsahu/E131_PixelPusher/blob/5a805c6a21932abc9e1756faad1bff146086f2e3/Arduino/E131_PixelPusher/E131_PixelPusher.ino#L210 In the example you linked it is an array of r, g & b.

**Comment by debsahu** [comment]
I tried exposing the buffer and bufferSize, let see if I succeed. Any ideas of how different this UART approach is from NeoPixelBus?

**Comment by simap** [comment]
> Is there a way to send uint8_t * data stored as array of r, g & b. Something like here: https://github.com/debsahu/E131_PixelPusher/blob/5a805c6a21932abc9e1756faad1bff146086f2e3/Arduino/E131_PixelPusher/E131_PixelPusher.ino#L210 In the example you linked it is an array of r, g & b.

Yeah, reference the buffer in the render callback function, and copy a different pixel in each invocation. If you have the data already, the internal buffer is redundant. The reason I wrote this driver was to primarily implement the just-in-time rendering for buffer-less setups where pixel data is calculated on the fly, but with a buffer fallback. 

The driver method is similar to NeoPixelBus UART method, and it might be a better option if you have the pixel data already, e.g. from over the network.

**Comment by debsahu** [comment]
Thanks for the help, I will take a stab at this this week. All RGB pixel data is sent directly over the network, I wanted to shift as many pixels as I can.
